name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Docker-compose
      run: docker-compose -f project_backend/docker-compose.yml build

    - name: test_books
      run: cd project_backend && docker-compose run books_service  python -m py.test book_service/tests/tests.py

    - name: test_issues
      run: cd project_backend && docker-compose run issues_service  python -m py.test issues_service/tests/tests.py

    - name: test_users
      run: cd project_backend && docker-compose run users_service  python -m py.test user_service/tests/tests.py

      
